[package]
authors.workspace      = true
description            = "Miden node token faucet"
edition.workspace      = true
homepage.workspace     = true
keywords               = ["faucet", "miden", "node"]
license.workspace      = true
name                   = "miden-faucet"
readme                 = "README.md"
repository.workspace   = true
rust-version.workspace = true
version                = "0.8.2"

[lints]
workspace = true

[dependencies]
anyhow                       = { workspace = true }
async-trait                  = "0.1"
axum                         = { version = "0.8", features = ["tokio"] }
axum-extra                   = { version = "0.10" }
base64                       = "0.21"
clap                         = { version = "4.5", features = ["derive", "string"] }
http                         = { workspace = true }
miden-lib                    = { workspace = true }
miden-node-proto             = { workspace = true }
miden-node-utils             = { workspace = true }
miden-objects                = { workspace = true }
miden-proving-service-client = { version = "0.8", features = ["tx-prover"] }
miden-tx                     = { workspace = true, features = ["concurrent"] }
rand                         = { workspace = true, features = ["thread_rng"] }
rand_chacha                  = "0.9"
serde                        = { version = "1.0", features = ["derive"] }
serde_json                   = { version = "1.0" }
thiserror                    = { workspace = true }
tokio                        = { workspace = true, features = ["fs"] }
tokio-stream                 = { workspace = true, features = ["net"] }
toml                         = { version = "0.8" }
tonic                        = { workspace = true, features = ["tls-native-roots"] }
tower                        = { workspace = true }
tower-http                   = { workspace = true, features = ["cors", "set-header", "trace"] }
tower_governor               = "0.7.0"
tracing                      = { workspace = true }
tracing-subscriber           = { workspace = true }
url                          = { workspace = true }
winter-maybe-async           = { version = "0.12" }

[build-dependencies]
# Required to inject build metadata.
miden-node-utils = { workspace = true, features = ["vergen"] }

[dev-dependencies]
fantoccini                = { version = "0.21" }
miden-node-block-producer = { workspace = true, features = ["testing"] }
miden-objects             = { workspace = true, features = ["testing"] }
serde_json                = { version = "1.0" }
tokio-stream              = { workspace = true, features = ["net"] }
tonic-web                 = { version = "0.12" }

# Required to avoid false positives in cargo-machete
# This is due to the `winter-maybe-async` crate not working standalone.
[package.metadata.cargo-machete]
ignored = ["async-trait"]
