timestamp = 1717344256
version   = 1

[[fungible_faucet]]
decimals     = 3
max_supply   = 100_000_000
storage_mode = "public"
symbol       = "MIDEN"

[[wallet]]
assets       = [{ amount = 999_000, symbol = "MIDEN" }]
storage_mode = "private"
# has_updatable_code = false # default value

[[wallet]]
assets       = [{ amount = 777, symbol = "MIDEN" }]
storage_mode = "private"
# has_updatable_code = false # default value
