name: Publish Release Artefacts

on:
  release:
    types: [prereleased, released]

  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (E.G. v0.10.0-rc.1, v0.10.0). Corresponding git tag must already exist."
        required: true
        type: string

env:
  version: ${{ inputs.version || github.ref_name }}
  registry: ghcr.io

permissions:
  id-token: write
  contents: write
  packages: write
  attestations: write

jobs:
  # DEBIAN
  publish-debian:
    name: Publish ${{ env.version }}-${{ matrix.arch }} Debian
    strategy:
      matrix:
        arch: [amd64, arm64]
    runs-on:
      labels: ${{ matrix.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@main
        with:
          ref: ${{ env.version}}
          fetch-depth: 0

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          # Only update the cache on push onto the next branch. This strikes a nice balance between
          # cache hits and cache evictions (github has a 10GB cache limit).
          save-if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/next' }}

      - name: Rust update
        run: |
          rustup update --no-self-update

      - name: Build packages
        uses: ./.github/actions/build_package
        with:
          gitref: ${{ env.version }}

      - name: Package names
        run: |
          echo "node-package=miden-node-${{ env.version }}-${{ matrix.arch }}.deb"     >> $GITHUB_ENV
          echo "faucet-package=miden-faucet-${{ env.version }}-${{ matrix.arch }}.deb" >> $GITHUB_ENV

      - name: Rename package files
        run: |
          mv miden-node.deb   ${{ env.node-package }}
          mv miden-faucet.deb ${{ env.faucet-package }}

      - name: shasum packages
        run: |
          sha256sum ${{ env.node-package }}   > ${{ env.node-package }}.checksum
          sha256sum ${{ env.faucet-package }} > ${{ env.faucet-package }}.checksum

      - name: Publish packages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ env.version }} \
            ${{ env.node-package }} \
            ${{ env.node-package }}.checksum \
            ${{ env.faucet-package }} \
            ${{ env.faucet-package }}.checksum \
            --clobber

  # DOCKER
  publish-docker:
    name: Publish ${{ inputs.version }} Docker
    strategy:
      matrix:
        component: [node]
    runs-on:
      labels: "ubuntu-latest"
    steps:
      - name: Checkout repo
        uses: actions/checkout@main
        with:
          ref: ${{ env.version}}
          fetch-depth: 0

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          file: ./bin/${{ matrix.component }}/Dockerfile
          tags: ${{ env.registry }}/0xmiden/miden-${{ matrix.component }}:${{ env.version }}
